#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Post-process a flowchart bitmap by removing the top title area.

Use when the source figure is maintained as a bitmap (not generated by matplotlib).

Example:
  python scripts/postprocess_fig8_remove_title.py --in "figures/fig8_method_selection_flowchart.png" --out "figures/fig8_method_selection_flowchart_no_title.png" --crop-top 120
"""
from __future__ import annotations

import argparse
from pathlib import Path


def main(inp: Path, out: Path, crop_top: int) -> None:
    from PIL import Image

    im = Image.open(inp)
    w, h = im.size
    crop_top = max(0, min(crop_top, h - 1))
    im2 = im.crop((0, crop_top, w, h))
    out.parent.mkdir(parents=True, exist_ok=True)
    # Keep DPI if present; otherwise default to 300 for journal usage.
    dpi = im.info.get("dpi") or (300, 300)
    if im2.mode in ("RGBA", "P"):
        bg = Image.new("RGB", im2.size, (255, 255, 255))
        if im2.mode == "RGBA":
            bg.paste(im2, mask=im2.split()[3])
        else:
            bg.paste(im2)
        im2 = bg
    else:
        im2 = im2.convert("RGB")
    im2.save(out, "PNG", dpi=dpi, compress_level=6)
    print(str(out))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", required=True, help="Input PNG path")
    ap.add_argument("--out", dest="out", required=True, help="Output PNG path")
    ap.add_argument("--crop-top", dest="crop_top", type=int, default=120, help="Pixels to crop from top")
    args = ap.parse_args()
    main(Path(args.inp), Path(args.out), args.crop_top)

